name: Lint

on:
  push:
    branches:
      - '**'
    paths-ignore:
      - '**.md'

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - uses: jdx/mise-action@v2

      - run: prek run --all-files --verbose --show-diff-on-failure
